// GENERATED by scripts/build-offers.mjs from docs/offers/*.md. Don't edit by hand:
// log the avis in docs/offers/, then run  node scripts/build-offers.mjs
// When a feed covers the shop day, it replaces that store's estimated offers.

const OFFER_FEEDS = [
  {
    store: 'bilka', week: '2026-W40', validFrom: '2026-09-24', validTo: '2026-10-01',
    source: 'docs/offers/bilka-2026-uge40.md',
    items: [
      {ing: 'chicken', name: 'Kyllingebrystfilet', size: 2600, label: '2.6 kg', price: 179},
      {ing: 'eggs', name: 'Dava danske frilandsæg', size: 600, label: '10 pcs', price: 28},
    ],
  },
  {
    store: 'fotex', week: '2026-W40', validFrom: '2026-09-24', validTo: '2026-10-01',
    source: 'docs/offers/foetex-2026-uge40.md',
    items: [
      {ing: 'eggs', name: 'Dava økologiske danske æg', size: 480, label: '8 pcs', price: 22},
    ],
  },
  {
    store: 'lidl', week: '2026-W40', validFrom: '2026-09-27', validTo: '2026-10-03',
    source: 'docs/offers/lidl-2026-uge40.md',
    items: [
      {ing: 'cottage', name: 'CHEASY Hytteost', size: 500, label: '500 g', price: 22},
      {ing: 'tuna', name: 'AMANDA Tun', size: 150, label: '150 g', price: 10},
      {ing: 'potatoes', name: 'Danske kartofler', size: 4000, label: '4 kg', price: 20},
      {ing: 'greenbeans', name: 'FRESHONA Grønne bønner', size: 1000, label: '1 kg', price: 14.95},
      {ing: 'onion', name: 'Danske rødløg', size: 750, label: '750 g', price: 8},
      {ing: 'smokedsalmon', name: 'Koldrøget, gravad eller varmrøget laks', size: 180, label: '180 g', price: 35},
      {ing: 'rice', name: 'ABU KASS Basmatiris', size: 4500, label: '4.5 kg', price: 95},
    ],
  },
  {
    store: 'netto', week: '2026-W40', validFrom: '2026-09-26', validTo: '2026-10-02',
    source: 'docs/offers/netto-2026-uge40.md',
    items: [
      {ing: 'chicken', name: 'Kyllingebrystfilet eller -inderfilet', size: 400, label: '400 g', price: 29},
      {ing: 'chickmince', name: 'Hakket dansk kyllingekød 7-10% eller kyllingelårfilet', size: 400, label: '400 g', price: 25},
      {ing: 'beeflean', name: 'Velsmag hakket oksekød 4-7%', size: 350, label: '350 g', price: 39.95},
      {ing: 'mixmince', name: 'Velsmag hakket okse- og grisekød 8-12%', size: 1000, label: '1 kg', price: 69},
      {ing: 'porkchop', name: 'Netto danske koteletter eller nakkekoteletter', size: 400, label: '400 g', price: 20},
      {ing: 'eggs', name: 'Dava danske frilandsæg', size: 480, label: '8 pcs', price: 24},
      {ing: 'smokedsalmon', name: 'Gravad, kold- eller varmrøget laks', size: 100, label: '100 g', price: 19},
      {ing: 'cheese', name: 'Mammen skiveost', size: 140, label: '140 g', price: 14},
      {ing: 'pasta', name: '1881 bronze pasta', size: 500, label: '500 g', price: 10},
      {ing: 'noodles', name: 'Fuldkornsnudler', size: 250, label: '250 g', price: 7},
      {ing: 'tortilla', name: 'Mex & Co. tortilla wraps', size: 370, label: '370 g', price: 9},
      {ing: 'potatoes', name: 'Samsø nemme kartofler', size: 650, label: '650 g', price: 10},
      {ing: 'apple', name: 'Danske æbler', size: 1500, label: '1.5 kg', price: 18},
      {ing: 'pesto', name: 'Løgismose pesto, hummus eller haydari', size: 150, label: '150 g', price: 20},
    ],
  },
  {
    store: 'rema', week: '2026-W40', validFrom: '2026-09-26', validTo: '2026-10-03',
    source: 'docs/offers/rema-2026-uge40.md',
    items: [
      {ing: 'pasta', name: 'Fuldkornspasta (økologisk)', size: 500, label: '500 g', price: 8},
      {ing: 'teriyaki', name: 'Teriyaki sauce', size: 260, label: '260 g', price: 12},
      {ing: 'salmon', name: 'Laksefileter eller rødspættefileter', size: 225, label: '225 g', price: 39},
      {ing: 'cod', name: 'Kullerfileter', size: 400, label: '400 g', price: 39},
    ],
  },
];
